version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: root
    - location: scripts/start_server
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      runas: root
