version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: root
    - location: scripts/start_server
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      runas: root
